### ISSUE TITLE
Story 1 : 사용자는 1개의 스크립트 당 N개 녹음 파일을 업로드할 수 있다.

### ISSUE THREAD

**Issue by sigridjineth** [DeliverBle/deliverble-backend-nestjs#92]
## Task
* [x] #89
* [ ] https://github.com/DeliverBle/deliverble-backend-nestjs/issues/91
* [ ] https://github.com/DeliverBle/deliverble-backend-nestjs/issues/94
* [ ] https://github.com/DeliverBle/deliverble-backend-nestjs/issues/95

## Bugfix
* not yet
